language: node_js

node_js:
  - node

matrix:
  include:

    #
    # Build using whatever is default on all platforms:
    #
    #   https://docs.travis-ci.com/user/reference/linux/
    #   https://docs.travis-ci.com/user/reference/osx/
    #   https://docs.travis-ci.com/user/reference/windows/
    #
    # except on precise where 10 is the latest that will run (newer require
    # a more modern glibc).
    #
    - name: 'Ubuntu 20.04 - Node.js LTS'
      os: linux
      dist: focal
    - name: 'Ubuntu 18.04 - Node.js LTS'
      os: linux
      dist: bionic
    - name: 'Ubuntu 16.04 - Node.js LTS'
      os: linux
      dist: xenial
    - name: 'Ubuntu 14.04 - Node.js LTS'
      os: linux
      dist: trusty
    - name: 'Ubuntu 12.04 - Node.js 10'
      os: linux
      dist: precise
      node_js: "10"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.8
    - name: 'Ubuntu 20.04 - Node.js LTS'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: focal
    - name: 'Ubuntu 18.04 - Node.js LTS'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: bionic
    - name: 'Ubuntu 16.04 - Node.js LTS'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: xenial
    - name: 'Ubuntu 14.04 - Node.js LTS'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: trusty
    - name: 'Ubuntu 12.04 - Node.js 10'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      dist: precise
      node_js: "10"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.8

    - name: 'Ubuntu - Node.js 14'
      os: linux
      node_js: "14"
    - name: 'Ubuntu - Node.js 12'
      os: linux
      node_js: "12"
    - name: 'Ubuntu - Node.js 10'
      os: linux
      node_js: "10"
    - name: 'Ubuntu - Node.js 8'
      os: linux
      node_js: "8"
    - name: 'Ubuntu - Node.js 6'
      os: linux
      node_js: "6"
    - name: 'Ubuntu - Node.js 4'
      os: linux
      node_js: "4"
    - name: 'Ubuntu - Node.js 0.12'
      os: linux
      node_js: "0.12"
    - name: 'Ubuntu - Node.js 0.10'
      os: linux
      node_js: "0.10"
    - name: 'Ubuntu - Node.js 14'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "14"
    - name: 'Ubuntu - Node.js 12'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "12"
    - name: 'Ubuntu - Node.js 10'
      os: linux
      node_js: "10"
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - name: 'Ubuntu - Node.js 8'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "8"
    - name: 'Ubuntu - Node.js 6'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "6"
    - name: 'Ubuntu - Node.js 4'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "4"
    - name: 'Ubuntu - Node.js 0.12'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "0.12"
    - name: 'Ubuntu - Node.js 0.10'
      os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      node_js: "0.10"
